networks:
  default:
    external:
      name : roboshop

services:
  mongodb:
    image : mongodb:1.0.1
    container_name: mongodb
  
  catalogue:
    image : catalogue:1.0.1
    container_name: catalogue
    depends_on:
    - mongodb

  web:
    image : web:1.0.0
    container_name: web
    ports:
      - "80:80"
    depends_on :
    - catalogue
    - user

  # redis:
  #   image : redis
  #   container_name: redis

  # user:
  #   image : user:1.0.1
  #   container_name: user
  #   depends_on:
  #     - redis
  #     - mongodb
  
  # cart:
  #   image : cart:1.0.1
  #   container_name: cart
  #   depends_on:
  #     - redis
  #     - catalogue



